### ISSUE TITLE
Delayed jobs with resque-web

### ISSUE THREAD

**Issue by tomhaigh** [gresrun/jesque#69]
The documentation says that it is possible to use the resque-web application to view the status of queues etc. I have tried this and it seems to work fine until I specify a delayed job, at which point resque-web starts failing with 500 errors. I have added resque-sheduler to resque-web but still have the same problem.

I wondered if the delayed job implementation use a different message format than resque-scheduler? Should I be using jesque-web instead of resque-web?

Thanks

**Comment by gresrun** [comment]
Hmm, I'm not sure what the issue is from your description. Are there any errors that resque-web emits?

**Comment by tomhaigh** [comment]
The error I am getting from resque-web is:

```
x.sparkol.local - - [03/Mar/2015:14:04:01 GMT Standard Time] "GET / HTTP/1.1" 302 0
- -> /
Redis::CommandError - ERR Operation against a key holding the wrong kind of value:
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:964:in `block in llen'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
        C:/Ruby21/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:963:in `llen'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-namespace-1.5.1/lib/redis/namespace.rb:392:in `call_with_namespace'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/redis-namespace-1.5.1/lib/redis/namespace.rb:289:in `method_missing'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque.rb:230:in `size'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/queues.erb:40:in `block (2 levels) in singleton class'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/queues.erb:37:in `each'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/queues.erb:37:in `block in singleton class'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/queues.erb:131067:in `instance_eval'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/queues.erb:131067:in `singleton class'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/queues.erb:131065:in `__tilt_29389152'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:665:in `erb'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server.rb:120:in `partial'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/overview.erb:1:in `block in singleton class'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/overview.erb:131067:in `instance_eval'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/overview.erb:131067:in `singleton class'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server/views/overview.erb:131065:in `__tilt_29389152'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:665:in `erb'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server.rb:139:in `show'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/resque-1.26.pre.0/lib/resque/server.rb:168:in `block (2 levels) in <class:Server>'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        C:/Ruby21/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        C:/Ruby21/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        C:/Ruby21/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2015-03-03 14:04:02] ERROR NoMethodError: undefined method `join' for #<String:0x4237020>
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        C:/Ruby21/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        C:/Ruby21/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        C:/Ruby21/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

It all works fine until I call `client.delayedEnqueue()` .

**Comment by gresrun** [comment]
OK, looks like redis.rb is trying to call llen() on a non-list key (likely the sorted set used as the data structure for delayed queues) while getting the size of each of the queues. 

I'm not sure why this is happening in resque-web, since I don't have tremendous knowledge of that software, but jesque-web should handle this case. If you encounter similar issues in jesque-web, I can do something about it.

**Comment by gresrun** [comment]
@tomhaigh Does this work correctly in Jesque-Web?

**Comment by tomhaigh** [comment]
Sorry, yes it doesn't cause any problems there, so I can use that instead. It just seems odd because I thought the redis data format was compatible between resque and jesque.

Thanks for looking at it

**Comment by gresrun** [comment]
After digging a bit more into the resque-scheduler implementation, it does appear that the delayed jobs feature is implemented quite differently in Jesque.

Basically, resque-scheduler clients add delayed jobs by appending job information into [three data structures](https://github.com/resque/resque-scheduler/blob/f0bb556167bd297ef3464e80d6b5b9bde0ab3fdd/lib/resque/scheduler/delaying_extensions.rb#L64) (a list, a set and and a zset) and then has at least one [dedicated scheduler](https://github.com/resque/resque-scheduler/blob/f0bb556167bd297ef3464e80d6b5b9bde0ab3fdd/lib/resque/scheduler.rb#L49) that [enqueues those delayed jobs into normal queues](https://github.com/resque/resque-scheduler/blob/f0bb556167bd297ef3464e80d6b5b9bde0ab3fdd/lib/resque/scheduler.rb#L189) (Redis lists) at the desired time and then workers pull off that job. This is quite different from Jesque's approach, in which clients immediately [enqueue a job into a special delayed queue](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/client/AbstractClient.java#L269) (a Redis zset) and workers pull off jobs from that delayed queue whose time has come to pass.

The resque-scheduler approach is quite a bit more complicated, requiring four Redis keys (two lists, a set and a zset) to enqueue a delayed job, and requires a scheduler must be running at the time the delayed job is ready in order to enqueue it into a regular queue. While I was not the original author of the delayed job feature (@anismiles was the [initial contributor](https://github.com/gresrun/jesque/commit/6bb5d53cd016e280ad213c8a579705d59998f7bd)), I feel the feature's incompatibility with resque-scheduler is acceptable given the benefits of simplicity and reliability of Jesque's current implementation of delayed queues.

**Comment by gresrun** [comment]
FYI, I [added a note to the README](https://github.com/gresrun/jesque/commit/103402e1efe95bef666438601b717dfda2950913) regarding the incompatibility with resque-scheduler.
